sudo: required
language: python

python: 2.7

services:
  - docker

install:
  - set -e
  - pip install -r ci/requirements.txt
  - pip install -r image/base/requirements.txt

script:
  - ./run-tests.sh
  - ci/ci.sh
